#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';

const read = (file) => fs.readFileSync(file, 'utf8');
const contract = JSON.parse(read('config/meta-phase31-facebook-realtime-cutover.json'));
const flags = JSON.parse(read('config/meta-phase31-cutover-flags.json'));
const envManifest = JSON.parse(read('config/env.manifest.json'));
const resolver = read('packages/meta-facebook-cutover-contract/src/index.ts');
const cutover = read('lib/meta-platform/domains/facebook/cutover.ts');
const bridge = read('lib/meta-platform/domains/facebook/legacy-bridge.ts');
const webhook = read('app/api/webhook/facebook/route.ts');
const worker = read('workers/meta-social.worker.ts');
const realtimeConfig = read('realtime-service/src/config.ts');
const realtimeApp = read('realtime-service/src/app.ts');
const realtimeIndex = read('realtime-service/src/index.ts');
const realtimeWebhook = read('realtime-service/src/routes/webhook.router.ts');
const handoff = read('realtime-service/src/realtime/main-app-facebook-handoff.ts');
const health = read('lib/meta-platform/admin/provider-health.ts');
const docs = read('docs/runbooks/meta-phase31-layer8-facebook-realtime-cutover.md');
const execution = JSON.parse(read('.ai/phase31-execution-manifest.json'));
const schema = read('prisma/schema.prisma');

const runtimeValues = ['LEGACY', 'SHADOW', 'PLATFORM', 'DOMAIN', 'LEGACY_ROLLBACK'];
assert.equal(contract.item, '8.5');
assert.deepEqual(contract.acceptedRuntimeValues, runtimeValues);
assert.equal(contract.shadowAuthority, 'LEGACY');
assert.equal(contract.platformAuthority, 'PLATFORM');
assert.equal(contract.invalidConfigurationPolicy, 'BLOCKED');
assert.equal(contract.duplicateEventBoundary, 'RAW_BODY_SHA256_AND_PAGE_ID');
assert.equal(contract.retryOwners.legacy, 'REALTIME_LEGACY');
assert.equal(contract.retryOwners.platform, 'MAIN_APP_BULLMQ');
assert.equal(contract.stabilityCriteria.maximumDuplicateEvents, 0);
assert.equal(contract.stabilityCriteria.maximumParallelRetryOwners, 0);
assert.equal(contract.stabilityCriteria.maximumLegacyDirectClientCallsInPlatformMode, 0);
assert.deepEqual(envManifest.enums.META_PHASE31_FACEBOOK_INBOX_RUNTIME, runtimeValues);
assert.deepEqual(flags.compatibilityControls.find((item) => item.name === 'META_PHASE31_FACEBOOK_INBOX_RUNTIME').acceptedValues, runtimeValues);
assert.match(read('.env.example'), /^META_PHASE31_FACEBOOK_INBOX_RUNTIME=LEGACY$/m);
assert.match(resolver, /legacyDirectClientEnabled: false, platformSyncEnabled: false/);
assert.match(resolver, /retryOwner: 'MAIN_APP_BULLMQ'/);
assert.match(resolver, /duplicateEventBoundary: 'RAW_BODY_SHA256_AND_PAGE_ID'/);
assert.match(cutover, /PARALLEL_RETRY_OWNERS_DETECTED/);
assert.match(cutover, /LEGACY_DIRECT_CLIENT_USED_IN_PLATFORM_MODE/);
assert.match(bridge, /assertFacebookPlatformSyncAuthority\(process\.env\)/);
assert.match(bridge, /shadowSideEffectsAllowed: false/);
assert.doesNotMatch(bridge, /syncRecentFacebookInboxLegacy\(/);
assert.match(webhook, /FACEBOOK_SHADOW_REQUIRES_SIGNED_LEGACY_MIRROR/);
assert.match(webhook, /requestKey: `\$\{digest\}:\$\{pageId\}`/);
assert.match(worker, /executeFacebookInboxSyncProduction/);
assert.match(realtimeConfig, /META_PLATFORM_LEGACY_FACEBOOK/);
assert.match(realtimeConfig, /resolveFacebookRealtimeCutover/);
assert.match(realtimeApp, /legacyDirectClientEnabled/);
assert.match(realtimeApp, /realtimeBridgeEnabled/);
assert.match(realtimeApp, /FACEBOOK_CUTOVER_BLOCKED/);
assert.match(realtimeIndex, /cutover\.retryOwner !== 'REALTIME_LEGACY'/);
assert.match(realtimeWebhook, /shadowPlatformEvaluationEnabled/);
assert.match(realtimeWebhook, /forwardFacebookWebhookToMainApp/);
assert.match(handoff, /x-realtime-bridge-signature/);
assert.match(health, /facebookRealtimeCutover/);
assert.match(docs, /one full processor|only full processor/i);
assert.match(docs, /Main-app BullMQ/);
assert.match(schema, /generator client/);
assert.equal(execution.layers['8'].items.find((item) => item.id === '8.5').status, 'COMPLETE');
assert.match(execution.current_item, /^(?:8\.[6-7]|9\.[1-8])$/);
assert.equal(execution.standard_item_contract.no_item_zip, true);
assert.equal(execution.standard_item_contract.full_layer_zip_only, true);

console.log('Phase 31 Layer 8.5 audit PASS');
console.log('- Singular Facebook provider and retry authority');
console.log('- Legacy direct Graph modules explicit and dynamically isolated');
console.log('- Shadow mirror is signed and platform evaluation is side-effect-free');
console.log('- Platform bridge disables legacy routes/workers');
console.log('- Prisma schema change: NONE');
