// app/admin/shortlist/mockShortlistData.ts
// Deterministic Ground Truth Mock Data matching Stitch Screen ID: 46092511627045dd9f65eaa0328dd890

import {
  ShortlistOrder,
  ShortlistStats,
  WholesaleSkuRow,
  WalkingRouteStep,
  WholesalePickListManifestData,
  ThermalReceiptPayload,
} from './types';

export const INITIAL_SHORTLIST_STATS: ShortlistStats = {
  pendingOrders: 10,
  productsRemaining: 16,
  productsTotal: 18,
  acquiredProducts: 2,
  acquiredPercentage: 11,
  expectedProfit: 18450,
  grossMarginPercent: 43.8,
  avgProfitPerOrder: 1845,
  totalOrderRevenue: 23780,
  wholesaleCost: 5330,
  roiPercent: 22,
};

export const INITIAL_SHORTLIST_ORDERS: ShortlistOrder[] = [
  {
    id: 'ord_65412890',
    orderNumber: '#ORD-65412890',
    createdAt: '2026-09-24T10:45:00.000Z',
    relativeTime: '15m ago',
    priority: 'URGENT',
    source: 'Direct Web Store',
    customer: {
      name: 'Ayesha Siddiqua',
      phone: '01712-345678',
      address: 'House 42, Road 11, Sector 4, Uttara, Dhaka',
      area: 'Uttara Sector 4',
    },
    items: [
      {
        id: 'item_lip_01',
        orderId: 'ord_65412890',
        productId: 'prod_lip_01',
        productName: 'Velvet Matte Liquid Lipstick - Ruby Rose',
        sku: 'MSB-LIP-01',
        barcode: '890123450912',
        quantity: 2,
        buyPrice: 320,
        sellPrice: 750,
        purchased: false,
        purchasedAt: null,
        priority: 'URGENT',
        supplierName: 'Paltan Heritage Trading',
        supplierPhone: '+880 1711-892401',
        verifiedBy: null,
        customerNote: 'কাস্টমার কনফার্ম করেছে, কালকে ডেলিভারি ড্রপ দিতে হবে',
      },
      {
        id: 'item_serum_01',
        orderId: 'ord_65412890',
        productId: 'prod_serum_01',
        productName: 'Hydrating Face Serum - 30ml',
        sku: 'MSB-SKN-001',
        barcode: '880954312001',
        quantity: 1,
        buyPrice: 880,
        sellPrice: 1650,
        purchased: false,
        purchasedAt: null,
        priority: 'URGENT',
        supplierName: 'Dhaka Cosmetics Importers Ltd.',
        supplierPhone: '+880 1822-445566',
        verifiedBy: null,
      },
    ],
    totalProducts: 3,
    purchasedProducts: 1,
    unpurchasedProducts: 2,
    progress: 33,
    isCompleted: false,
    totalBuyCost: 1520,
    totalCustomerBill: 3150,
    totalProfit: 1630,
  },
  {
    id: 'ord_32109876',
    orderNumber: '#ORD-32109876',
    createdAt: '2026-09-24T11:00:00.000Z',
    relativeTime: '28m ago',
    priority: 'NORMAL',
    source: 'Facebook Messenger',
    customer: {
      name: 'Nusrat Jahan',
      phone: '01823-998877',
      address: 'Flat 3B, Lake View Tower, Dhanmondi 27, Dhaka',
      area: 'Dhanmondi',
    },
    items: [
      {
        id: 'item_lip_02',
        orderId: 'ord_32109876',
        productId: 'prod_lip_01',
        productName: 'Velvet Matte Liquid Lipstick - Ruby Rose',
        sku: 'MSB-LIP-01',
        barcode: '890123450912',
        quantity: 1,
        buyPrice: 320,
        sellPrice: 750,
        purchased: false,
        purchasedAt: null,
        priority: 'NORMAL',
        supplierName: 'Paltan Heritage Trading',
        supplierPhone: '+880 1711-892401',
      },
    ],
    totalProducts: 1,
    purchasedProducts: 0,
    unpurchasedProducts: 1,
    progress: 0,
    isCompleted: false,
    totalBuyCost: 320,
    totalCustomerBill: 750,
    totalProfit: 430,
  },
];

// ─────────────────────────────────────────────────────────────
// Screen 46092511627045dd9f65eaa0328dd890 Ground Truth Rows
// ─────────────────────────────────────────────────────────────

export const INITIAL_WHOLESALE_SKUS: WholesaleSkuRow[] = [
  {
    id: 'sku_lip_01',
    sku: 'MSB-LIP-01',
    barcode: '890123450912',
    title: 'Velvet Matte Lipstick',
    variantOrShade: 'Ruby Rose',
    volumeSpec: '3.2ml',
    categoryTag: 'Lips',
    batchFormulaNote: 'Batch LK-24 Long Wear',
    requiredQuantity: 3,
    demandTag: 'Required',
    priority: 'URGENT',
    linkedOrders: [
      { orderId: 'ord_65412890', orderNumber: '#ORD-65412890', quantity: 2, shippingType: 'Express' },
      { orderId: 'ord_32109876', orderNumber: '#ORD-32109876', quantity: 1, shippingType: 'Standard' },
    ],
    vendor: {
      stallName: 'Paltan Heritage Trading',
      zone: 'Paltan',
      standLocation: 'Stand 14, Lane 2, Paltan',
      contactPerson: 'Babul',
      phone: '+880 1711-892401',
      isVerified: true,
      statusTag: 'Verified Vendor · In Stock',
      statusTagType: 'verified',
    },
    financials: {
      unitCost: 320,
      totalCost: 960,
      retailValue: 2250,
      netProfit: 1290,
      marginPercent: 57.3,
    },
    pickedQuantity: 1,
    progressPercent: 33,
    statusNote: 'Picked 1 pc',
    isAcquired: false,
  },
  {
    id: 'sku_serum_01',
    sku: 'MSB-SKN-001',
    barcode: '880954312001',
    title: 'Hydrating Face Serum',
    variantOrShade: 'Hyaluronic',
    volumeSpec: '30ml',
    categoryTag: 'Skincare',
    batchFormulaNote: 'Deep Hydration Formula',
    requiredQuantity: 2,
    demandTag: 'Urgent Stock',
    priority: 'URGENT',
    linkedOrders: [
      { orderId: 'ord_88129034', orderNumber: '#ORD-88129034', quantity: 1 },
      { orderId: 'ord_90234112', orderNumber: '#ORD-90234112', quantity: 1 },
    ],
    vendor: {
      stallName: 'Dhaka Cosmetics Importers',
      zone: 'Chawkbazar',
      standLocation: 'Chawkbazar Bhaban 3, Shop 204',
      contactPerson: 'Tanvir Bhai',
      phone: '+880 1822-445566',
      isVerified: true,
      statusTag: 'Hold ends 1:00 PM today',
      statusTagType: 'urgent',
    },
    financials: {
      unitCost: 880,
      totalCost: 1760,
      retailValue: 3300,
      netProfit: 1540,
      marginPercent: 46.7,
    },
    pickedQuantity: 0,
    progressPercent: 0,
    statusNote: 'Hold expiring soon',
    isAcquired: false,
  },
  {
    id: 'sku_centella_01',
    sku: 'MSB-SKN-088',
    barcode: '880912349088',
    title: 'Centella Soothing Gel',
    variantOrShade: 'Cica Calm',
    volumeSpec: '200ml',
    categoryTag: 'K-Beauty',
    batchFormulaNote: 'Barrier Relief Formula',
    requiredQuantity: 4,
    demandTag: 'Bulk Source',
    priority: 'NORMAL',
    linkedOrders: [
      { orderId: 'ord_77112001', orderNumber: '#ORD-77112001', quantity: 2 },
      { orderId: 'ord_44901238', orderNumber: '#ORD-44901238', quantity: 2 },
    ],
    vendor: {
      stallName: 'Korea Beauty Direct BD',
      zone: 'Elephant Rd',
      standLocation: 'Elephant Road, Multiplan L4',
      contactPerson: 'Minhaj',
      phone: '+880 1912-778899',
      statusTag: 'Master Carton Ready',
      statusTagType: 'default',
    },
    financials: {
      unitCost: 550,
      totalCost: 2200,
      retailValue: 5000,
      netProfit: 2800,
      marginPercent: 56.0,
    },
    pickedQuantity: 1,
    progressPercent: 25,
    statusNote: '3 pcs pending pickup',
    isAcquired: false,
  },
  {
    id: 'sku_niacin_01',
    sku: 'MSB-SRM-030',
    barcode: '890881230030',
    title: 'Niacinamide 10% Serum',
    variantOrShade: 'Zinc 1%',
    volumeSpec: '30ml',
    categoryTag: 'Pore Refiner',
    batchFormulaNote: 'High Active Concentration',
    requiredQuantity: 3,
    demandTag: 'Required',
    priority: 'HIGH',
    linkedOrders: [
      { orderId: 'ord_55321908', orderNumber: '#ORD-55321908', quantity: 2 },
      { orderId: 'ord_88231004', orderNumber: '#ORD-88231004', quantity: 1 },
    ],
    vendor: {
      stallName: 'Pure Glow Trade',
      zone: 'Chawkbazar',
      standLocation: 'Chawkbazar Lane 4, Stand 18',
      contactPerson: 'Imtiaz',
      phone: '+880 1733-909012',
      statusTag: 'Ready for Handover',
      statusTagType: 'default',
    },
    financials: {
      unitCost: 720,
      totalCost: 2160,
      retailValue: 5400,
      netProfit: 3240,
      marginPercent: 60.0,
    },
    pickedQuantity: 0,
    progressPercent: 0,
    statusNote: 'Awaiting batch verification',
    isAcquired: false,
  },
  {
    id: 'sku_snail_01',
    sku: 'MSB-SKN-096',
    barcode: '880941647000',
    title: 'Snail Mucin 96 Essence',
    variantOrShade: 'COSRX Auth',
    volumeSpec: '100ml',
    categoryTag: 'Essence',
    batchFormulaNote: 'QR Authenticated Batch',
    requiredQuantity: 2,
    demandTag: 'Required',
    priority: 'NORMAL',
    linkedOrders: [
      { orderId: 'ord_99014522', orderNumber: '#ORD-99014522', quantity: 1 },
      { orderId: 'ord_33100299', orderNumber: '#ORD-33100299', quantity: 1 },
    ],
    vendor: {
      stallName: 'Asian Skin Logistics',
      zone: 'Paltan',
      standLocation: 'Paltan Plaza L2, Rm 218',
      contactPerson: 'Zahidul',
      phone: '+880 1819-332211',
      statusTag: 'Consignment Partner',
      statusTagType: 'default',
    },
    financials: {
      unitCost: 1100,
      totalCost: 2200,
      retailValue: 4700,
      netProfit: 2500,
      marginPercent: 53.2,
    },
    pickedQuantity: 0,
    progressPercent: 0,
    statusNote: 'Priority 2 pickup',
    isAcquired: false,
  },
  {
    id: 'sku_rosemist_01',
    sku: 'MSB-HYD-100',
    barcode: '890442310100',
    title: 'Organic Rose Mist',
    variantOrShade: 'Distilled',
    volumeSpec: '100ml',
    categoryTag: 'Botanical',
    batchFormulaNote: 'Alcohol Free Floral',
    requiredQuantity: 2,
    demandTag: 'Required',
    priority: 'NORMAL',
    linkedOrders: [
      { orderId: 'ord_10928471', orderNumber: '#ORD-10928471', quantity: 2 },
    ],
    vendor: {
      stallName: 'Organic Herbal Imports',
      zone: 'Chawkbazar',
      standLocation: 'Chawkbazar Main, Bldg 12',
      contactPerson: 'Shamsul',
      phone: '+880 1688-219455',
      statusTag: 'Stock Verified',
      statusTagType: 'verified',
    },
    financials: {
      unitCost: 280,
      totalCost: 560,
      retailValue: 1300,
      netProfit: 740,
      marginPercent: 56.9,
    },
    pickedQuantity: 0,
    progressPercent: 0,
    statusNote: 'Pending Chawkbazar drop',
    isAcquired: false,
  },
];

// ─────────────────────────────────────────────────────────────
// Default Manifest & Walking Route (Batch #PL-84920)
// ─────────────────────────────────────────────────────────────

export const DEFAULT_PICK_LIST_MANIFEST: WholesalePickListManifestData = {
  batchNumber: 'PL-84920',
  selectedSkusCount: 2,
  selectedUnitsCount: 5,
  totalCashFloat: 2720,
  hubsCovered: 'Paltan & Chawk',
  qualityProtocolChecked: true,
  runnerName: 'Shakil',
  runnerCode: 'MSB-R04',
  walkingSteps: [
    {
      stepIndex: 1,
      marketName: 'PALTAN MARKET',
      unitsInStep: 3,
      vendorName: 'Paltan Heritage Trading',
      stallAddress: 'Stand 14, Lane 2, Paltan Market',
      phone: '+880 1713-892401',
      contactName: 'Ismat Hossain',
      itemTitle: 'Velvet Matte Liquid Lipstick',
      variantOrShade: 'Ruby Rose',
      skuCode: 'MSB-LIP-01',
      volumeSpec: '3.2ml',
      orderAllocations: [
        { orderNumber: '#ORD-654138', quantity: 2, shippingType: 'Express' },
        { orderNumber: '#ORD-321098', quantity: 1, shippingType: 'Standard' },
      ],
      unitCost: 320,
      totalCost: 960,
      unitsPicked: 1,
      totalUnitsRequired: 3,
    },
    {
      stepIndex: 2,
      marketName: 'CHAWKBAZAR BHABAN',
      unitsInStep: 2,
      vendorName: 'Dhaka Cosmetics Importers Ltd.',
      stallAddress: 'Shop 204, 2nd Floor, Chawkbazar Bhaban 3',
      phone: '+880 1820-445566',
      contactName: 'Tanvir Bhai',
      itemTitle: 'Hydrating Face Serum',
      variantOrShade: 'Hyaluronic B5',
      skuCode: 'MSB-SER-001',
      volumeSpec: '50ml',
      orderAllocations: [
        { orderNumber: '#ORD-98129084', quantity: 1 },
        { orderNumber: '#ORD-98254132', quantity: 1 },
      ],
      unitCost: 880,
      totalCost: 1760,
      unitsPicked: 0,
      totalUnitsRequired: 2,
      warningAlert: 'Hold expires 1:00 PM today - Inform Tanvir before pickup',
    },
  ],
};

export const DEFAULT_THERMAL_RECEIPT: ThermalReceiptPayload = {
  slipNumber: 'PL-84920',
  rigId: 'RIG #04',
  dateTimeStr: '24 Sep 2026 • 11:42 AM',
  hubLocation: 'Dhaka Hub • Chawkbazar & Paltan',
  walkingRouteSummary: [
    '1. Paltan Stand 14 (Heritage Trading)',
    '2. Chawkbazar Shop 204 (Dhaka Cosmetics)',
  ],
  lineItems: [
    {
      title: 'VELVET MATTE LIPSTICK',
      shadeOrType: 'Ruby Rose',
      skuCode: 'MSB-LIP-01',
      volumeSpec: '3.2ml',
      qty: 3,
      unitPrice: 320,
      totalPrice: 960,
      orderRefs: ['#ORD-654138 (2x Expr)', '#ORD-321098 (1x)'],
    },
    {
      title: 'HYDRATING FACE SERUM',
      shadeOrType: 'Hyaluronic',
      skuCode: 'MSB-SER-001',
      volumeSpec: '50ml',
      qty: 2,
      unitPrice: 880,
      totalPrice: 1760,
      orderRefs: ['#ORD-98129084 (1x)', '#ORD-98254132 (1x)'],
    },
  ],
  totalUnits: 5,
  totalSkus: 2,
  requiredCashFloat: 2720,
  settlementMethod: 'Cash Handover at Stall',
  barcodeString: '* PL-84920-R15B1 *',
  runnerName: 'Shakil',
  dispatchInCharge: 'Tanvir (Ops Lead)',
};
