export const ADMIN_PERMISSIONS = {
  DASHBOARD: 'dashboard',
  PRODUCTS_VIEW: 'products_view',
  PRODUCTS_CREATE: 'products_create',
  PRODUCTS_EDIT: 'products_edit',
  PRODUCTS_DELETE: 'products_delete',
  ORDERS_VIEW: 'orders_view',
  ORDERS_PROCESS: 'orders_process',
  ORDERS_REFUND: 'orders_refund',
  CUSTOMERS_VIEW: 'customers_view',
  CUSTOMERS_EDIT: 'customers_edit',
  CUSTOMERS_DELETE: 'customers_delete',
  ANALYTICS_VIEW: 'analytics_view',
  SETTINGS_VIEW: 'settings_view',
  SETTINGS_EDIT: 'settings_edit',
  USERS_MANAGE: 'users_manage',
  CONTENT_MANAGE: 'content_manage',
} as const;

export type AdminPermission =
  (typeof ADMIN_PERMISSIONS)[keyof typeof ADMIN_PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, AdminPermission[]> = {
  SUPER_ADMIN: Object.values(ADMIN_PERMISSIONS),
  ADMIN: [
    ADMIN_PERMISSIONS.DASHBOARD,
    ADMIN_PERMISSIONS.PRODUCTS_VIEW,
    ADMIN_PERMISSIONS.PRODUCTS_CREATE,
    ADMIN_PERMISSIONS.PRODUCTS_EDIT,
    ADMIN_PERMISSIONS.PRODUCTS_DELETE,
    ADMIN_PERMISSIONS.ORDERS_VIEW,
    ADMIN_PERMISSIONS.ORDERS_PROCESS,
    ADMIN_PERMISSIONS.CUSTOMERS_VIEW,
    ADMIN_PERMISSIONS.CUSTOMERS_EDIT,
    ADMIN_PERMISSIONS.ANALYTICS_VIEW,
    ADMIN_PERMISSIONS.SETTINGS_VIEW,
    ADMIN_PERMISSIONS.CONTENT_MANAGE,
  ],
  MANAGER: [
    ADMIN_PERMISSIONS.DASHBOARD,
    ADMIN_PERMISSIONS.PRODUCTS_VIEW,
    ADMIN_PERMISSIONS.PRODUCTS_EDIT,
    ADMIN_PERMISSIONS.ORDERS_VIEW,
    ADMIN_PERMISSIONS.ORDERS_PROCESS,
    ADMIN_PERMISSIONS.CUSTOMERS_VIEW,
    ADMIN_PERMISSIONS.ANALYTICS_VIEW,
    ADMIN_PERMISSIONS.CONTENT_MANAGE,
  ],
  STAFF: [
    ADMIN_PERMISSIONS.DASHBOARD,
    ADMIN_PERMISSIONS.PRODUCTS_VIEW,
    ADMIN_PERMISSIONS.ORDERS_VIEW,
    ADMIN_PERMISSIONS.CUSTOMERS_VIEW,
  ],
};

export function getAdminPermissions(role: string): AdminPermission[] {
  return ROLE_PERMISSIONS[role] || [];
}
