export const UI_LANGUAGE_POLICY = {
  root: 'en',
  storefront: 'en',
  admin: 'en',
  customerAccount: 'en',
  customerTransaction: 'bn-BD',
  bengaliContent: 'bn-BD',
} as const;

export const UI_COPY = {
  common: {
    close: 'Close',
    back: 'Back',
    retry: 'Try again',
    loading: 'Loading…',
    unavailable: 'Temporarily unavailable',
  },
  commonBn: {
    close: 'বন্ধ করুন',
    back: 'ফিরে যান',
    retry: 'আবার চেষ্টা করুন',
    loading: 'লোড হচ্ছে…',
    unavailable: 'সাময়িকভাবে পাওয়া যাচ্ছে না',
    home: 'হোমে ফিরে যান',
  },
  cart: {
    add: 'Add to cart',
    added: 'Added to cart',
    empty: 'Your cart is empty',
    selectVariant: 'Select a variant',
    outOfStock: 'Out of stock',
    quantity: 'Quantity',
    subtotal: 'Subtotal',
  },
  auth: {
    loginTitle: 'Log in to your account',
    invalidCredentials: 'The email or password is incorrect.',
    suspended: 'This account is suspended. Please contact support.',
    loginFailed: 'Login failed. Please try again.',
    networkError: 'Network error. Check your internet connection and try again.',
    googleFailed: 'Google sign-in could not be completed.',
    facebookFailed: 'Facebook sign-in could not be completed.',
  },
  routeErrors: {
    storefront: {
      title: 'We could not load this page',
      description: 'A temporary problem prevented the page from loading. Please try again.',
      backLabel: 'Go to home page',
    },
    product: {
      title: 'We could not load this product',
      description: 'Please try again, or return to the shop to browse other products.',
      backLabel: 'Back to shop',
    },
    checkout: {
      title: 'চেকআউট পেজটি লোড করা যায়নি',
      description: 'সাময়িক সমস্যার কারণে চেকআউট দেখানো যাচ্ছে না। আবার চেষ্টা করুন।',
      backLabel: 'কার্টে ফিরে যান',
    },
    account: {
      title: 'We could not load your account',
      description: 'Your account data is safe. Please try loading this section again.',
      backLabel: 'Account overview',
    },
    admin: {
      title: 'Admin page could not be loaded',
      description: 'A temporary problem interrupted this admin screen. Please try again.',
      backLabel: 'Admin dashboard',
    },
  },
  checkout: {
    free: 'ফ্রি',
    deliveryOfferApplied: 'ডেলিভারি অফার প্রযোজ্য হয়েছে',
    saved: 'সাশ্রয়',
    genericError: 'অর্ডারটি সম্পন্ন করা যায়নি। আবার চেষ্টা করুন।',
    changedDetails: 'চেকআউটের তথ্য পরিবর্তিত হয়েছে। তথ্য যাচাই করে আবার অর্ডার করুন।',
    homeDeliveryUnavailable: 'নির্বাচিত এলাকায় হোম ডেলিভারি পাওয়া যাচ্ছে না। অন্য এলাকা নির্বাচন করুন।',
    areaZoneMismatch: 'নির্বাচিত এলাকা এই জোনের সঙ্গে মেলে না। এলাকা আবার নির্বাচন করুন।',
    invalidPhone: 'বাংলাদেশের সঠিক ১১ সংখ্যার মোবাইল নম্বর লিখুন।',
    streetRequired: 'বাসা, রাস্তা বা বিস্তারিত ঠিকানা লিখুন।',
    fullNameRequired: 'আপনার পুরো নাম লিখুন।',
    cityRequired: 'শহর নির্বাচন করুন।',
    zoneRequired: 'জোন নির্বাচন করুন।',
    areaRequired: 'এলাকা নির্বাচন করুন।',
    cartEmpty: 'আপনার কার্ট খালি। চেকআউটের আগে একটি পণ্য যোগ করুন।',
    paymentRequired: 'পেমেন্ট পদ্ধতি নির্বাচন করুন।',
    calculatingDelivery: 'ডেলিভারি চার্জ হিসাব করা হচ্ছে।',
    deliveryCalculationFailed: 'ডেলিভারি চার্জ হিসাব করা যায়নি। শহর, জোন ও এলাকা যাচাই করুন।',
    placingOrder: 'অর্ডার করা হচ্ছে…',
    loginToOrder: 'অর্ডার করতে লগইন করুন',
    completeDetails: 'চেকআউটের তথ্য সম্পূর্ণ করুন',
    placeOrder: 'অর্ডার করুন',
    continueToPayment: 'পেমেন্টে এগিয়ে যান',
    networkError: 'নেটওয়ার্কে সমস্যা হয়েছে। ইন্টারনেট সংযোগ যাচাই করে আবার চেষ্টা করুন।',
  },
} as const;
